server:
  tomcat:
    accesslog:
      enabled: true

spring:

  application:
    name: app

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  profiles:
    active: development

  main:
    banner-mode: off

logging:
  level:
    org.springframework.security: DEBUG
    # Логирование Spring Framework
    org.springframework: INFO
    # Детальное логирование Spring Web
    org.springframework.web: DEBUG
    # Логирование Hibernate
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    # Логирование вашего приложения
    hexlet.code.app: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://670f1aa31d58f3f0b117d222726d6c01@o4508717065109504.ingest.de.sentry.io/4508717075136592
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
