server:
  tomcat:
    accesslog:
      enabled: true

spring:

  application:
    name: app

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  profiles:
    active: development

  main:
    banner-mode: off

logging:
  level:
    org.springframework.security: DEBUG
    # Логирование Spring Framework
    org.springframework: INFO
    # Детальное логирование Spring Web
    org.springframework.web: DEBUG
    # Логирование Hibernate
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    # Логирование вашего приложения
    hexlet.code.app: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

